import type { QualificationGroup } from "@/types/profile";

export const qualificationGroups: QualificationGroup[] = [
  {
    id: "programming-languages",
    title: "Programming languages",
    items: [
      "JavaScript",
      "Java",
      "C#",
      "Dart",
      "PHP",
      "Python",
      "HTML5",
      "VisualBasic.NET",
      "C/C++",
      "MySQL",
      "Swift",
    ],
  },
  {
    id: "frameworks-platforms",
    title: "Frameworks and platforms",
    items: [
      "React",
      "React Native",
      "Flutter",
      "Angular",
      "Vue",
      "Node.js",
      "Tailwind CSS",
      "Bootstrap",
      "Material UI",
      ".NET",
      "WordPress",
      "Kotlin",
      "Spring Boot",
      "Django",
      "Ruby",
      "Flask",
      "Salesforce Cloud",
    ],
  },
  {
    id: "tools-engines",
    title: "Tools and engines",
    items: [
      "Visual Studio Code",
      "Unity Game Engine",
      "PlayCanvas",
      "SQL Server",
      "Workbench",
      "Insomnia",
      "Sourcetree",
      "Postman",
      "NetBeans IDE",
      "Macromedia Dreamweaver",
      "Dev-C++",
      "Brackets",
      "Visual Studio",
    ],
  },
  {
    id: "methodologies-security",
    title: "Methodologies and security",
    items: [
      "Scrum",
      "SDLC",
      "Cascade",
      "Lean Six Sigma",
      "Ethical hacking",
      "Passive, semi-passive, and active data collection",
      "Vulnerability mapping",
      "CCNA1",
      "CCNA2",
    ],
  },
];

export const personalInterests = [
  "Cybersecurity",
  "Software development",
  "Videogame development",
  "VR and app development",
  "Music",
  "Audio-visual entertainment",
  "Reading",
  "Computer hardware maintenance",
  "Videogames",
  "Traveling",
  "Technology",
] as const;
